[project]
name = "numberly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rein Van Imschoot", email = "reinvanimschoot@proton.me" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.142.2",
    "python-multipart>=0.0.32",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
numberly-predict = "numberly.predict:main"
numberly-train = "numberly.train:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
